### ISSUE TITLE
Create script on Cadastro.js

### ISSUE THREAD

**Issue by paulo-ti** [paulo-ti/cerimonialista_virtual#6]
Create script for insert  on FireBase

**Comment by LukkzMaverick** [comment]
Este user.uid seria o firebase.auth().currentUser, que foi carregado juntamente com a página.

function updateUser(e){
    e.preventDefault();
    try{
        const refUsers = firebase.database().ref("users")
        var nomeCompleto = document.getElementById('nomeCompleto').value;
        console.log(document.getElementById('sexoM').value);
        let radios = document.getElementsByName("sexo");
        let sexo;
        for (let i = 0; i < radios.length; i++) {
            if (radios[i].checked) {
                sexo = radios[i].value;
            }
        }
        var telefone = document.getElementById('telefone').value;
        var dataNascimento = document.getElementById('dataNascimento').value;
        if(document.getElementById('receberEmail').checked == true)
            var emailsPromocionais = true;
        else
            var emailsPromocionais = false;
        if(document.getElementById('receberWpp').checked == true)
            var notificacaoWhatsApp = true;
        else
            var notificacaoWhatsApp = false;
        var updateData = {nomeCompleto: nomeCompleto,sexo: sexo ,telefone: telefone, dataNascimento: dataNascimento, emailsPromocionais : emailsPromocionais, notificacaoWhatsApp : notificacaoWhatsApp};
        refUsers.child(user.uid).update(updateData).then(()=>{
            alert("Dados Atualizados com Sucesso!");
        });
    }catch(e){
        alert("Não foi possível atualizar os dados.");
        console.log(e);
    }
}
